# Generated by Django 6.0.4 on 2026-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('shortlisted', 'ShortListed'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
    ]
